budowlanka_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', 'mainapp')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
"""Defines URL patterns for budowlanka_v2 project"""

from django.urls import path

from . import views

app_name = 'budowlanka_project'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    # Blog page
    path('blog/', views.blog, name='blog'),

    # Detail page for a single entry on blog
    path('blog/<int:entry_id>/', views.detail, name='detail'),

    # Contact page
    path('kontakt/', views.contact, name='contact'),
]

mainapp/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Realization(models.Model):
    """
    Represents a project or task completion.

    Attributes:
        title (str): The title of the realization.
        content (str): The description of the realization.
        date (datetime): The date and time when the realization was added.
    """
    title = models.CharField(max_length=100, verbose_name="Tytuł")  # Title of the realization
    content = models.CharField(max_length=1000, verbose_name="Opis")  # Description of the realization
    date = models.DateTimeField(default=timezone.now,
                                verbose_name="Data dodania")  # Date and time when the realization was added
    image = models.ImageField(upload_to='realizations_images/', null=True, blank=True, verbose_name="Zdjęcie główne") # Image of the realization

    def __str__(self):
        """
        Returns a string representation of the realization.

        Returns:
            str: Title of the realization.
        """
        return self.title

    class Meta:
        verbose_name_plural = "Realizacje"  # Plural name for the Realization model
        ordering = ['-date']  # Default ordering by date


class RealizationImage(models.Model):
    """
    Represents a project image.

    Attributes:
        realization (Realization): The associated realization.
        image (str): Image of the realization.
    """
    realization = models.ForeignKey(Realization, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='realizations_images/')

    def __str__(self):
        return f"{self.realization.title} Image"

mainapp/forms.py
from django import forms


class ContactForm(forms.Form):
    """
    Simple contact form for collecting user messages.

    Attributes:
        first_name (CharField): Field for the first name with customized widget attributes.
        last_name (CharField): Field for the last name with customized widget attributes.
        email (EmailField): Field for the email address with customized widget attributes.
        message (CharField): Field for the message content with a textarea widget and customized attributes.
    """
    first_name = forms.CharField(label='', max_length=100, widget=forms.TextInput(
        attrs={'placeholder': 'Imie', 'style': 'width: 300px', 'class': 'form-control'}))  # Field for the first name
    last_name = forms.CharField(label='', max_length=100, widget=forms.TextInput(
        attrs={'placeholder': 'Nazwisko', 'style': 'width: 300px', 'class': 'form-control'}))  # Field for the last name
    email = forms.EmailField(label='', widget=forms.TextInput(attrs={'placeholder': 'Email', 'style': 'width: 300px',
                                                                     'class': 'form-control'}))  # Field for the
    # email address
    message = forms.CharField(label='', widget=forms.Textarea(
        attrs={'placeholder': 'Wiadomość', 'style': 'width: 300px',
               'class': 'form-control'}))  # Field for the message content with a textarea widget

mainapp/views.py
import logging
from calendar import HTMLCalendar

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.views.decorators.http import require_http_methods

from .forms import ContactForm
from .models import Realization, RealizationImage

# Get an instance of a logger
logger = logging.getLogger(__name__)


def index(request):
    """
    Render the home page for Budowlanka.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The rendered home page.
    """
    try:
        logger.debug("Renderowanie strony głównej")
        return render(request, 'mainapp/index.html')
    except Exception as e:
        logger.error(f"Problem przy renderowaniu strony głównej: {e}")
        return render(request, 'mainapp/error.html', {'error': str(e)})


def blog(request):
    """
    Show all entries and main image (if it exists).

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The rendered blog page with paginated entries.
    """
    try:
        entries = Realization.objects.all()
        paginator = Paginator(entries, 10)  # Paginate with 10 entries per page
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {'page_obj': page_obj}
        logger.debug("Pobrano część wpisów")
        return render(request, 'mainapp/blog.html', context=context)
    except Realization.DoesNotExist:
        logger.error("Żadne wpisy nie istnieją")
        raise Http404("Żaden wpis nie istnieje")
    except Exception as e:
        logger.error(f"Błąd podczas pobierania wpisów: {e}")
        return render(request, 'mainapp/error.html', {'error': str(e)})


@require_http_methods(["GET", "POST"])
def detail(request, entry_id):
    """
    Show entry, its comments and images.

    Args:
        request (HttpRequest): The request object.
        entry_id (int): The ID of the entry.

    Returns:
        HttpResponse: The rendered detail page of the entry.
    """
    try:
        entry = get_object_or_404(Realization, pk=entry_id)
        images = RealizationImage.objects.filter(realization=entry)

        context = {'entry': entry, 'images': images}
        logger.debug(f"Widok szczegółowy dla realizacji {entry_id}")
        return render(request, 'mainapp/detail.html', context)
    except Realization.DoesNotExist:
        logger.error(f"Realizacja o id {entry_id} nie istnieje")
        raise Http404("Podany wpis nie istnieje")
    except Exception as e:
        logger.error(f"Błąd w widoku szczegółowym dla realizacji {entry_id}: {e}")
        return render(request, 'mainapp/error.html', {'error': str(e)})


@require_http_methods(["GET", "POST"])
def contact(request):
    """
    Render the contact page and handle form submission.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The rendered contact page.
    """
    try:
        if request.method == 'POST':
            # POST data submitted
            form = ContactForm(data=request.POST)
            if form.is_valid():
                # Form is valid; process the data
                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']
                email = form.cleaned_data['email']
                message = form.cleaned_data['message']

                send_mail(
                    f'Wiadomość od {first_name} {last_name}',
                    message,
                    email,
                    ['wojtek.jurkowicz@gmail.com'],
                    fail_silently=False,
                )

                messages.success(request, "Wiadomość została wysłana.")
                logger.info(f"Wiadomość wysłana przez {request.user}")
                return redirect('mainapp:index')
            else:
                logger.error(f"Formularz wiadomości nie jest poprawny: {form.errors}")
        else:
            # No data submitted
            form = ContactForm()
            logger.debug("Renderowanie formularza kontaktowego")

        context = {'form': form}
        return render(request, 'mainapp/contact.html', context)
    except Exception as e:
        logger.error(f"Błąd w widoku wiadomości: {e}")
        return render(request, 'mainapp/error.html', {'error': str(e)})

mainapp/templates/mainapp/base.html
<!doctype html>
<!-- blue: #127586 border: #1a6374
     red: #bf0c0c border: 632935
     grey: #313445 border: 2e4050-->
<html lang="PL-pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <title>Jasion Dachy</title>
        {% load django_bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        {% load static %}
    <style>
        div
        {
            #border: 1px red solid;
            margin-bottom: 20px;

        }
        a
        {
            #border: 3px green solid;
            #border-radius: 5px;
            #padding: 5px;
            #font-size: 15pt;
            color: #127586;
        }
        .text-blue,p
        {
            color: white;
        }
        body
        {
            background-color: #313445;
            color: #127586;
            max-width: 99%;

        }
        article
        {
            background-color: #2c2e3c;
            border-radius: 10px;
            padding: 15px;
            margin-bottom: 20px;
        }
        gmp-map
        {
            background-color: #2c2e3c;
            border-radius: 10px;
            padding: 15px;
            margin-bottom: 30px;
            height: 600px;
            max-height: 100%;
        }
        .padding
        {
            padding: 10px;
        }
        .blog_img
        {
            max-width: 450px;
            height: auto;
            border-radius: 10px;
        }
         .carousel-item img {
            #height: 300px;
            #width: auto;
            margin: 0 auto;
        }
    </style>
</head>
<body>
    <div class = "container-fluid">
        <div class = "row" style="font-size: large;">
            <div class="col-12">
               <nav class="navbar navbar-expand-lg justify-content-center">
                     <a class="navbar-brand" href="{% url 'budowlanka_project:index' %}"><img class="img-responsive rounded-circle" src="{% static 'mainapp/logo.jpg' %}" alt="Logo" style="max-height: 80px;"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ">
                            <li class="nav-item active"><a class="nav-link text-blue" href="{% url 'budowlanka_project:index' %}">Strona główna</a></li>
                            <li class="nav-item"><a class="nav-link text-blue" href="{% url 'budowlanka_project:blog' %}">Aktualności</a></li>
                            <li class="nav-item"><a class="nav-link text-blue" href="{% url 'budowlanka_project:contact' %}">Kontakt</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        </div>
        <div class = "container-fluid container-md-8">
            <div class="row" >
                {% block content %}{% endblock content %}
            </div>
         <div class="row" style="position: relative;">
             <article>
                 <h1 class="col text-center">Prace wykonali</h1>
                 <p class="col text-center">Nikodem Jasionowski<br>Jakub Jaworski<br>Wojciech Jurkowicz<br>Adrianna Kolenda</p>

             </article>
            </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    </body>
</html>

mainapp/templates/mainapp/blog.html
{% extends 'mainapp/base.html' %}

{% block content %}

<div class="col-12">

    <h1>Aktualności</h1>
        {% for entry in page_obj %}
                <article class="">
                    <a href="/blog/{{ entry.id }}"><h3>{{ entry.title }}</h3></a>
                    <div class = "row">
                        <div class = "col-8 order-first" style="font-size: large">{{ entry.content|linebreaks }}</div>
                        {% if entry.image %}
                            <div class="col-4 order-last d-flex flex-row-reverse">
                                <img class="blog_img" src="{{ entry.image.url }}" alt="{{ entry.title }}">
                            </div>
                        {% endif %}
                    </div>
                    <p>Dodano: {{ entry.date }}</p>
                </article>
        {% empty %}
            Nic tu jeszcze nie ma
        {% endfor %}

    {% if page_obj.has_other_pages %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; pierwsza</a>
                    <a href="?page={{ page_obj.previous_page_number }}">poprzednia</a>
                {% endif %}

                <span class="current">
                    Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">następna</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">ostatnia &raquo;</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
</div>

{% endblock content %}

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}

{% block content %}
<div class="col-xxl-4 order-xxl-last col-md-12 order-md-first" style="padding: 5px;">
    <article>
        <h2>Kontakt:</h2>
        <ul style="list-style-type:none; font-size: large" class="text-blue">
            <li><i class="fas fa-map-marker-alt "></i> Adres: ul. Przykładowa 123, 00-000 Warszawa</li>
            <li><i class="fas fa-phone-alt"></i> Telefon: +48 123 456 789</li>
            <li><i class="fas fa-envelope"></i> E-mail: kontakt@example.com</li>
        </ul>
        </article>

            <script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBb2UF9YukDAeKX_UrmlnmGp9D5iiZVu9w&callback=console.debug&libraries=maps,marker&v=beta">
            </script>
            <gmp-map center="54.110198974609375,22.935564041137695" zoom="14" map-id="DEMO_MAP_ID" class="col-12">
                <gmp-advanced-marker position="54.110198974609375,22.935564041137695" title="My location"></gmp-advanced-marker>
            </gmp-map>
</div>
<div class="col-xxl-8 order-xxl-first col-md-12 order-md-last">
        <article>
        <div style="max-width: 350px; margin:auto">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
            <h1>Napisz do nas wiadomość</h1>
            <form action="{% url 'budowlanka_project:contact' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" name="submit" class="btn btn-primary">Wyślij</button>
            </form>
        </div>

    </article>
</div>
{% endblock content %}

mainapp/templates/mainapp/detail.html
{% extends 'mainapp/base.html' %}

{% block content %}
<div class="col-12">
        <article>
    <h1>{{ entry.title }}</h1>
    <div class = "row">
        <div class = "col-8 order-first" style="font-size: x-large">{{ entry.content|linebreaks }}</div>
            <div class="col-4">
                 <div id="carouselExample" class="carousel slide" data-ride="carousel">

                    <div class="carousel-inner">
                {% for img in images %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                            <img src="{{ img.image.url }}" alt="Image for {{ entry.title }}" class="d-block w-100 blog_img" >
                        </div>
                {% empty %}

                    <p>Brak dodatkowych zdjęć</p>
                {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExample" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
    </div>

    <p>Dodano: {{ entry.date }}</p>
    </article>

</div>

{% endblock content %}

mainapp/templates/mainapp/error.html
<html lang="pl-PL">
<head>
    <title>Błąd</title>
</head>
<body>
    <h1>Coś poszło nie tak...</h1>
    <p>{{ error }}</p>
</body>
</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% block content %}
<div class="col-xxl-4 order-xxl-last col-md-12 order-md-first" style="padding: 5px;">
        {% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
    <script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBb2UF9YukDAeKX_UrmlnmGp9D5iiZVu9w&callback=console.debug&libraries=maps,marker&v=beta">
    </script>
    <gmp-map center="54.110198974609375,22.935564041137695" zoom="14" map-id="DEMO_MAP_ID">
      <gmp-advanced-marker position="54.110198974609375,22.935564041137695" title="My location"></gmp-advanced-marker>
    </gmp-map>
</div>
<div class="col-xxl-8 order-xxl-first col-md-12 order-md-last">
    <article>
        <h1>Jasion Dachy</h1>
        <p>
            Od 10 lat na rynku<br>
            Wykonaliśmy około 315 prac<br>
        </p>
        <h4>Współpracujemy z firmami takimi jak:</h4>
        <p>
            - Blachy pruszyński,<br>
            - Creaton,<br>
            - oraz przede wszystkim z Polskim Stowarzyszeniem Dekarzy w Białymstoku<br>
        </p>
            <h4>Nasza oferta:</h4>
        <p>
            - przede wszystkim dekarstwem oraz blacharstwem,<br>
            - usługi ciesielskie,<br>
            - wszelkie prace murarskie (np. stan surowy, elewacje)<br>
            - usługi transportowe<br><br>
            Wykorzystujemy najwyższej jakości materiały zapewniane przez pobliskie firmy. Ogromną uwagę przykładamy do obróbki dostarczonych nam materiałów.
        </p>
    </article>
</div>
{% endblock content %}

mainapp/templates/mainapp/realization_pdf_template.html
<!-- realization_pdf_template.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Realization PDF</title>
</head>
<body>
    <h1>Realizations</h1>
    <table>
        <thead>
            <tr>
                <th>Title</th>
                <th>Content</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            {% for realization in data %}
                <tr>
                    <td>{{ realization.title }}</td>
                    <td>{{ realization.content }}</td>
                    <td>{{ realization.date }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>